### ISSUE TITLE
USER STORY: As a Site User I can create a new recipe to share with other users

### ISSUE THREAD

**Issue by DaniCarmo** [DaniCarmo/Yummy-Blog#1]
EPIC: <epic>

As a **Site User** I can **create a new recipe** so that **I can share it with others**

**Acceptance Criteria**

- [ ] - Recipe form has a title, description, category, image and ingredients 
- [ ] - The user can add as many ingredients as needed 
- [ ] - The user can preview the recipe before submitting it 
- [ ] - After submitting the recipe, the user is redirected to the recipe detail page 
- [ ] - If the user tried to create a recipe without being logged in, they are redirected to the log in page

**Tasks**

- [ ] Task 1: Design and implement new recipe 
- [ ] Task 2: Implement recipe upload functionality 
- [ ] Task 3: Add recipe validation and error handling 
- [ ] Task 4: Test recipe creation functionality
